# Generated by Django 4.2.3 on 2023-08-08 08:05

import book_service.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=book_service.models.book_cover_file_path,
            ),
        ),
    ]
