# Generated by Django 4.2.3 on 2023-08-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
